name: Knox Go Build

on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.3

      - name: Install mockgen
        run: |
          go install github.com/golang/mock/mockgen@v1.6.0

      - name: Build
        run: |-
          make build

      - name: Test
        run: |-
          make test
