// Code generated by MockGen. DO NOT EDIT.
// Source: ./presentation/presentation.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	params "github.com/knox-networks/knox-go/params"
	credential_adapter "github.com/knox-networks/knox-go/service/credential_adapter"
)

// MockPresentationClient is a mock of PresentationClient interface.
type MockPresentationClient struct {
	ctrl     *gomock.Controller
	recorder *MockPresentationClientMockRecorder
}

// MockPresentationClientMockRecorder is the mock recorder for MockPresentationClient.
type MockPresentationClientMockRecorder struct {
	mock *MockPresentationClient
}

// NewMockPresentationClient creates a new mock instance.
func NewMockPresentationClient(ctrl *gomock.Controller) *MockPresentationClient {
	mock := &MockPresentationClient{ctrl: ctrl}
	mock.recorder = &MockPresentationClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPresentationClient) EXPECT() *MockPresentationClientMockRecorder {
	return m.recorder
}

// Request mocks base method.
func (m *MockPresentationClient) Request(p params.RequestPresentationParams) (*credential_adapter.PresentationChallenge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Request", p)
	ret0, _ := ret[0].(*credential_adapter.PresentationChallenge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Request indicates an expected call of Request.
func (mr *MockPresentationClientMockRecorder) Request(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Request", reflect.TypeOf((*MockPresentationClient)(nil).Request), p)
}

// Share mocks base method.
func (m *MockPresentationClient) Share(p params.SharePresentationParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Share", p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Share indicates an expected call of Share.
func (mr *MockPresentationClientMockRecorder) Share(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Share", reflect.TypeOf((*MockPresentationClient)(nil).Share), p)
}
